version: '3.7'

services:
  web:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.master
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./vendor:/mnt/vendor

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

  smtpfake:
    image: mailhog/mailhog

volumes:
  odoo-web-data:
  odoo-db-data:
